services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  # Only for development
  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    ports:
      - 18080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
      - ./develop_only/pgadmin/servers.json:/pgadmin4/servers.json
      - ./develop_only/pgadmin/pgpass:/pgpass
    env_file:
      - .env
    depends_on:
      - db
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - backend
volumes:
  volume_postgres:
    name: v_postgres
  volume_pgadmin:
    name: v_pgadmin
